### ISSUE TITLE
lasertemp maximum from config file is not overriding default values

### ISSUE THREAD

**Issue by clemniem** [mrbeam/MrBeamPlugin#202]
If in the In MrBeam2B.profile the settings are:
```
laser:
   max_temperature: 30.0
   hysteresis_temperature: 27.0
   cooling_duration: 25
```

The loaded values are still:
`2017-10-27 07:24:35,812 - octoprint.plugins.mrbeam.iobeam.temperaturemanager - INFO - TemperatureManager initialized. temperature_max: 55.0`
