### ISSUE TITLE
QuickText fonts not working in PROD mode

### ISSUE THREAD

**Issue by Gallore** [mrbeam/MrBeamPlugin#222]
QuickText fonts are visible in UI but not in `temp.svg` and not on the actual engraving result.
This is only, if the device is in PROD mode, precisely if the `devel` section below is NOT present in config.yaml.

```
devel:
  cache:
    enabled: false
  webassets:
    bundle: false
    clean_on_startup: true
    minify: false
```
