### ISSUE TITLE
Shutdown/Reboot button is not showing up

### ISSUE THREAD

**Issue by make-ing** [mrbeam/MrBeamPlugin#3]
A user mentioned that the "Shutdown/Reboot" button is not showing up anymore.

**Comment by make-ing** [comment]
Clemens can you check if this is true (a bug)? And if so fix it :)

**Comment by hungerpirat** [comment]
could be a config file / OctoPi related thing

**Comment by make-ing** [comment]
it is indeed a config file problem. You need to add the following to the config.yaml file:

```
system:
  action
  - name: Shutdown
    action: shutdown
    command: sudo shutdown -h now
    confirm: You are about to shutdown the system.
  - name: Reboot
    action: reboot
    command: sudo shutdown -r now
    confirm: You are about to reboot the system.
```
