### ISSUE TITLE
default config announcement settings

### ISSUE THREAD

**Issue by hungerpirat** [mrbeam/MrBeamPlugin#77]
octoprint's announcemnet channels should be disabled - and maybe our own ones should be enabled instead.

```yaml  
    announcements:
    channels:
      _important:
        read_until: 1478614200
      _news:
        read_until: 1481906700
      _octopi:
        read_until: 1490979600
      _plugins:
        read_until: 1494460800
      _releases:
        read_until: 1494514800
      _spotlight:
        read_until: 1481719500
    enabled_channels:
    - _news
    - _octopi
    - _plugins
    - _releases
    - _spotlight
```
