### ISSUE TITLE
Camera: Broken pic_settings.yaml prevents user from re-doing camera calibration.He's trapped

### ISSUE THREAD

**Issue by Gallore** [mrbeam/MrBeamPlugin#859]
If the pic_settings.yaml file is nor really valid, it should be ignored which then allows the suer to redo a camera calibration.
Currently a user can not re-do a camera calibration in this case.

Example of a corrupted file: (notice the two null values!)
```
calibMarkers:
  NE:
  - 1886
  - 166
  NW:
  - null
  - null
  SE:
  - 1892
  - 1268
  SW:
  - 204
  - 1350
```
