### ISSUE TITLE
beamOS image: Add SW update data for OctoPrint to config.yaml

### ISSUE THREAD

**Issue by Gallore** [mrbeam/MrBeamPlugin#91]
Octoprint section in config.yaml 
```plugins > softwareupdate > checks``` should look like this:
```
      octoprint:
        checkout_folder: /home/pi/OctoPrint
        stable_branch:
          branch: mrbeam2-stable
        user: mrbeam
```

Where user points to our repo instead of Gina's. This will cause the SW check mechanism to use our repot to check for new versions instead of Gina's
